language: ruby
rvm:
    - 2.3
services:
    - postgresql
install:
    - gem install bundler
    - bundle install --jobs=3 --retry=3 --deployment
before_script:
    - psql -c 'create database upmach_test;' -U postgres
    - bin/rails db:migrate
script:
    - bin/rails test
git:
    depth: 3